name: dreamers
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  # For carousel_slider -> Swiper
  carousel_slider: ^4.2.1

  # For percent bar
  percent_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  card_swiper: ^2.0.4

flutter:
  uses-material-design: true

  # Logo icon
  assets:
    - assets/images/logo.png
