/// Flutter icons Flamingo
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Flamingo
///      fonts:
///       - asset: fonts/Flamingo.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Flamingo {
  Flamingo._();

  static const _kFontFam = 'Flamingo';
  static const String? _kFontPkg = null;

  static const IconData logo =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logoCircular =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logoCuteBlack =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logoCuteWhite =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logoSearch =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
