# Generated by Django 4.1.7 on 2023-07-03 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation_size', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fund_transfered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=50)),
                ('sub_heading', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('full_detail', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('keyword', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(default='profile_placeholder.png', upload_to='profile')),
                ('donations_made', models.IntegerField(blank=True, default=0, null=True)),
                ('story_made', models.IntegerField(blank=True, default=0, null=True)),
                ('total_donation_size', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item')),
                ('thumbnail', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='base.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryFinance',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_fund_request_size', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('current_donated_size', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('donations', models.ManyToManyField(blank=True, related_name='storyfinance_donations', to='base.donation')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='finance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story_finance', to='base.storyfinance'),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='story_tag', to='base.storytag'),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='story_user', to='base.userprofile'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_story', to='base.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='base.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='doner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='donation_user', to='base.userprofile'),
        ),
    ]
