# Generated by Django 4.1.7 on 2023-04-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyapplicationschema',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_monthly', to='base.applicationschema'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplicationschema',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_scholarship', to='base.applicationschema'),
        ),
    ]
