# Generated by Django 4.1.7 on 2023-04-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationschema',
            name='keyword',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
