# Generated by Django 4.1.7 on 2023-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_applicationschema_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='story_category', to='base.applicationschema'),
        ),
    ]
